-- SentraGrid — Initial Schema Migration
-- Run this in Supabase SQL Editor after enabling pgvector extension

-- Enable pgvector
create extension if not exists vector;

-- Plant zones (static reference data)
create table zones (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  zone_type text not null, -- 'confined_space', 'hot_work_area', 'general', 'storage'
  x_coord float not null,  -- position on the plant layout SVG (0-1000 scale)
  y_coord float not null,
  width float default 120.0,
  height float default 80.0,
  baseline_risk_level text default 'low' -- low/medium/high
);

-- Sensors (gas, temperature, pressure)
create table sensors (
  id uuid primary key default gen_random_uuid(),
  zone_id uuid references zones(id),
  sensor_type text not null, -- 'gas_h2s', 'gas_co', 'temperature', 'pressure'
  unit text not null
);

create table sensor_readings (
  id bigserial primary key,
  sensor_id uuid references sensors(id),
  value float not null,
  recorded_at timestamptz default now()
);

-- Index for fast time-series queries
create index idx_sensor_readings_sensor_time on sensor_readings(sensor_id, recorded_at desc);

-- Permits to work
create table permits (
  id uuid primary key default gen_random_uuid(),
  zone_id uuid references zones(id),
  permit_type text not null, -- 'hot_work', 'confined_space_entry', 'electrical', 'general'
  status text not null default 'active', -- active/closed/pending
  issued_by text,
  issued_at timestamptz default now(),
  valid_until timestamptz,
  override_justification text,
  override_officer text
);

-- Workers (for geospatial layer)
create table workers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text
);

create table worker_positions (
  id bigserial primary key,
  worker_id uuid references workers(id),
  zone_id uuid references zones(id),
  recorded_at timestamptz default now()
);

create index idx_worker_positions_worker_time on worker_positions(worker_id, recorded_at desc);

-- Alerts generated by the risk engine
create table alerts (
  id uuid primary key default gen_random_uuid(),
  zone_id uuid references zones(id),
  severity text not null, -- 'info', 'warning', 'critical'
  title text not null,
  explanation text not null,   -- human-readable reasoning from the agent
  triggering_factors jsonb,    -- e.g. {"gas_reading": 82, "active_permit": "hot_work", "threshold": 60}
  status text default 'open',  -- open/acknowledged/resolved
  created_at timestamptz default now()
);

create index idx_alerts_status on alerts(status);
create index idx_alerts_zone on alerts(zone_id);

-- Incident/near-miss corpus for RAG
create table incident_reports (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null,
  embedding vector(384),  -- matches all-MiniLM-L6-v2 output dimension
  source text  -- 'near_miss_log', 'oisd_guideline', 'factory_act'
);

-- Vector similarity RPC used by backend RAG service
create or replace function match_incident_reports(
  query_embedding vector(384),
  match_count int default 5
)
returns table (
  id uuid,
  title text,
  content text,
  source text,
  similarity float
)
language sql
as $$
  select
    ir.id,
    ir.title,
    ir.content,
    ir.source,
    1 - (ir.embedding <=> query_embedding) as similarity
  from incident_reports ir
  where ir.embedding is not null
  order by ir.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;

-- Enable Realtime on key tables
alter publication supabase_realtime add table alerts;
alter publication supabase_realtime add table sensor_readings;
alter publication supabase_realtime add table worker_positions;
alter publication supabase_realtime add table permits;
